services:
  - type: web
    name: receta-veterinaria-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: receta-veterinaria-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: info

databases:
  - name: receta-veterinaria-db
    databaseName: receta_veterinaria
    user: receta_admin
    plan: free